2022-04-30 14:44:22,047 - INFO -   File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\trixi\experiment\experiment.py", line 89, in run
    self.train(epoch=self._epoch_idx)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\experiment_template.py", line 140, in train
    for batch_idx, batch in tqdm(enumerate(train_batches), desc="Train"):

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:

  File "D:\git\DL4H-Project\TPC-LoS-prediction\eICU_preprocessing\eicu_dataset2.py", line 249, in __iter__
    for batch in self.data_loader:

2022-04-30 14:44:22,047 - INFO - AttributeError("'EICUReaderAdapter2' object has no attribute 'data_loader'")
