2022-04-09 13:58:36,794 - INFO -   File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\trixi\experiment\experiment.py", line 78, in run
    self.setup()

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\run_tpc.py", line 14, in setup
    no_flat_features=self.train_datareader.no_flat_features).to(device=self.device)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\tpc_model.py", line 108, in __init__
    self.model_type = config.model_type

2022-04-09 13:58:36,794 - INFO - AttributeError("'Config' object has no attribute 'model_type'")
